### PR TITLE
Use `reregisterurl` to move datalad remotes to web

### LINKED ISSUE #35: unembargo: move URLs from "datalad" to "web" remote
Joey implemented a new command `reregisterurl` in [10.20240227-39-g016d1bee88](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=016d1bee88dfac29325a88b75765cb269321905d)  with [this example shown](https://git-annex.branchable.com/forum/how_to___34__move__34___URL_between_remotes__63__/#comment-33ac483fdeb025eb2b6714d9c4dafe8f)

```
joey@darkstar:~/tmp/x>git-annex registerurl WORM--bar http://example.com/bar.foo
registerurl http://example.com/bar.foo ok

joey@darkstar:~/tmp/x> git-annex whereis --key WORM--bar
whereis WORM--bar (1 copy)
    dca0b5f9-659a-4928-84db-ff9fd74d8fc8 -- [foo]

  foo: http://example.com/bar.foo
ok

joey@darkstar:~/tmp/x>git-annex reregisterurl WORM--bar --move-from=foo
reregisterurl WORM--bar ok

joey@darkstar:~/tmp/x>git-annex whereis --key WORM--bar
whereis WORM--bar (2 copies)
    00000000-0000-0000-0000-000000000001 -- web
    dca0b5f9-659a-4928-84db-ff9fd74d8fc8 -- [foo]

  web: http://example.com/bar.foo
ok
```
so upon unembargo we could migrate URLs from `datalad` special remote to regular `web` and populate direct S3 URLs.

### PR DESCRIPTION
**Pull request by jwodder**
Closes #35.

### CODE REVIEW

**Comment by jwodder** [comment]
Now blocked by the fact that this requires git-annex 10.20240430 but neurodebian still only has 10.20240227.

CC @yarikoptic

**Comment by jwodder** [comment]
Correction: While the outdated git-annex is a problem, the current test failures are actually due to https://github.com/dandi/dandi-archive/issues/1943.

**Comment by yarikoptic** [comment]
I removed git and git-annex packages in that conda env (`dandisets-2`) so we should be ready to merge/deploy this to prevent datasets failing their updates.

Note that it seems that subsequent update on the failed dataset just proceeds forward, so we might need to get back to those which once were private and migrate "retroactively" -- please add some support command or script for doing that.

**Comment by jwodder** [comment]
@yarikoptic This can't be merged, as the tests are still failing due to https://github.com/dandi/dandi-archive/issues/1943.

**Comment by jwodder** [comment]
@yarikoptic The tests are finally passing now, and I've created a separate PR in dandi/dandisets for adding a script for backfilling the `reregisterurl` invocations: https://github.com/dandi/dandisets/pull/387

**Comment by yarikoptic** [comment]
Thank you!  Let's get it in!

**Pull request merged**
