### PR TITLE
Work around a change in Git's behavior

### PR DESCRIPTION
**Pull request by jwodder**

### CODE REVIEW

**Comment by yarikoptic** [comment]
this is unrelated to
- https://github.com/dandi/backups2datalad/issues/40
?

**Comment by jwodder** [comment]
@yarikoptic Completely unrelated.  This is about timestamps emitted by Git; that issue is about timestamps emitted by Dandi Archive.

**Comment by yarikoptic** [comment]
interesting... just odd that we are going the opposite directions here whenever in 
- https://github.com/dandi/dandisets/pull/384
modifying assets to have "Z" instead of `+00:00`

**Comment by jwodder** [comment]
@yarikoptic I opted for `+00:00` here because that's the format used by Python's `datetime.isoformat()` method, while `Z` seems to be produced by Pydantic 2.x.

**Pull request merged**
